# Bayesian Classifier

In [2]:
# Import LabelEncoder
from sklearn import preprocessing
#for data manipulation
import pandas as pd
#naive bayesian classifier model
from sklearn.naive_bayes import GaussianNB 
#for data operation
import numpy as np

In [3]:
golf = pd.read_csv("golf.csv")
golf = golf.drop(["Unnamed: 5"] ,axis = 1)
golf

,OUTLOOK,TEMPERATURE,HUMIDITY,WINDY,PLAY GOLF
0,Rainy,Hot,High,False,No
1,Rainy,Hot,High,True,No
2,Overcast,Hot,High,False,Yes
3,Sunny,Mild,High,False,Yes
4,Sunny,Cool,Normal,False,Yes
5,Sunny,Cool,Normal,True,No
6,Overcast,Cool,Normal,True,Yes
7,Rainy,Mild,High,False,No
8,Rainy,Cool,Normal,False,Yes
9,Sunny,Mild,Normal,False,Yes


In [4]:
le = preprocessing.LabelEncoder()
# Converting string labels into numbers.
outlook = le.fit_transform(golf["OUTLOOK"]).reshape(-1, 1)
temperature = le.fit_transform(golf["TEMPERATURE"]).reshape(-1, 1)
humidity = le.fit_transform(golf["HUMIDITY"]).reshape(-1, 1)
windy = le.fit_transform(golf["WINDY"]).reshape(-1, 1)
play_golf = le.fit_transform(golf["PLAY GOLF"]).reshape(-1, 1)

#Combinig different features into single listof tuples
#features = np.concatenate((outlook, temperature, humidity, windy), axis = 1)
#features = np.concatenate((outlook, temperature.T), axis = 0)
features_pd = pd.DataFrame(outlook, columns = ['outlook'])
features_pd['temperature'] = temperature
features_pd['humidity'] = humidity
features_pd['windy'] = windy
print(features_pd)
features = features_pd.to_numpy()
features

    outlook  temperature  humidity  windy
0         1            1         0      0
1         1            1         0      1
2         0            1         0      0
3         2            2         0      0
4         2            0         1      0
5         2            0         1      1
6         0            0         1      1
7         1            2         0      0
8         1            0         1      0
9         2            2         1      0
10        1            2         1      1
11        0            2         0      1
12        0            1         1      0
13        2            2         0      1


array([[1, 1, 0, 0],
       [1, 1, 0, 1],
       [0, 1, 0, 0],
       [2, 2, 0, 0],
       [2, 0, 1, 0],
       [2, 0, 1, 1],
       [0, 0, 1, 1],
       [1, 2, 0, 0],
       [1, 0, 1, 0],
       [2, 2, 1, 0],
       [1, 2, 1, 1],
       [0, 2, 0, 1],
       [0, 1, 1, 0],
       [2, 2, 0, 1]], dtype=int64)

In [5]:
#Create a Gaussian Classifier
model = GaussianNB()

features.reshape(-1, 2)
# Train the model using the training sets
model.fit(features,play_golf)

#Predict Output
predicted= model.predict([[2,0,1,0]]) # sunny, hot, normal, false
print("Predicted Value:", predicted)
if predicted == 1:
    print("Golf play : Yes")
else:
     print("Golf play : No")   

Predicted Value: [1]
Golf play : Yes


c:\users\dell\appdata\local\programs\python\python36\lib\site-packages\sklearn\naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


   # Iris Flower Dataset

In [6]:
from sklearn.datasets import load_iris

In [11]:
iris = load_iris()
print(len(iris.data))
train_X = iris.data[:125, :]
print(train_X)
test_X = iris.data[126:, :]
print(test_X)
train_Y = iris.target[:125]
test_Y = iris.target[126:]

150
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.

In [54]:
iris_model = GaussianNB()
iris_model.fit(train_X, train_Y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [55]:
expected = test_Y
predicted = iris_model.predict(test_X)

In [56]:
iris_model.score(test_X, test_Y)

0.9166666666666666